version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: sh -c " python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - ./backend:/home/app/web
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    env_file:
      - ./frontend/.env.development.local
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env.dev

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A config worker -l info
    depends_on:
      - backend
      - redis
      - db
    restart: on-failure
    env_file:
      - ./backend/.env.dev

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A config beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile /tmp/celerybeat.pid
    depends_on:
      - backend
      - redis
      - db
    restart: on-failure
    env_file:
      - ./backend/.env.dev

  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '5555:5555'
    command: "celery -A config flower --address=0.0.0.0"
    depends_on:
      - celery
    env_file:
      - ./backend/.env.dev

volumes:
  postgres_data:
  redis_data:
