version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: sh -c " python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - ./backend:/home/app/web
      - stats_file:/home/app/frontend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      db:
        condition: service_started
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
      - ./frontend:/app
      - stats_file:/home/app/frontend
    ports:
      - 8080:8080
    env_file:
      - ./frontend/.env.development.local
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env.dev

volumes:
  postgres_data:
  stats_file:
