version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py collectstatic --no-input --clear && python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 "
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - frontend_volume:/app
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_started
      frontend:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm run build
    ports:
      - 8080:8080
    env_file:
      - ./frontend/.env.production.local
    volumes:
      - frontend_volume:/app

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1317:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_volume:
