FROM python:3.10-alpine

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
ENV STATS_FILE=/home/app/frontend
RUN mkdir -p $APP_HOME && mkdir -p $STATS_FILE
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.dev.txt .
RUN pip install -r requirements.dev.txt

COPY . .