FROM python:3.9.7-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
ENV STATS_FILE=/home/app/frontend
RUN mkdir -p $APP_HOME && mkdir -p $STATS_FILE
WORKDIR $APP_HOME

RUN apk update && \
	apk add gcc python3-dev jpeg-dev zlib-dev musl-dev libjpeg py3-setuptools \
	tiff-dev openjpeg-dev freetype-dev lcms2-dev \
	libwebp-dev tcl-dev tk-dev harfbuzz-dev fribidi-dev libimagequant-dev \
	libxcb-dev libpng-dev alpine-sdk build-base openssl-dev tzdata py3-tz

RUN pip install --upgrade pip
COPY ./requirements.dev.txt .
RUN pip install -r requirements.dev.txt

COPY . .

COPY startup.sh /startup.sh
RUN chmod 744 /startup.sh

EXPOSE 8000

CMD ["/startup.sh"]