# Generated by Django 3.2.9 on 2022-08-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=255, verbose_name='サイズ')),
                ('image', models.ImageField(upload_to='', verbose_name='商品画像')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('start_datetime', models.DateTimeField(verbose_name='開始時間')),
                ('end_datetime', models.DateTimeField(verbose_name='終了時間')),
                ('status', models.IntegerField(choices=[(0, '予約中'), (1, '開催中'), (2, '終了')], verbose_name='状態')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(verbose_name='購入個数')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='購入時間')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.vote')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
