# Generated by Django 3.2.9 on 2022-08-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
